# VPN iperf config.
#iperf_vpn:
iperf:
  description: Run iperf over vpn 
  flags:
    iperf_vpn_sending_thread_count: 5
    vpn_service_gateway_count: 1 # AWS only allows 1
    use_vpn: True
    #use_capacity_reservations: False
  vpn_service:
    tunnel_count: 2  # create multiple tunnels for ecmp load balance testing
    shared_key: DEADBEEF
    ike_version: 1
    routing_type: static
  vm_groups:
    vm_1:
      cloud: GCP
      cidr: 10.0.1.0/24
      zone: us-west1-b      
      vm_spec: 
        GCP:
            machine_type: n1-standard-4
            #zone: us-central1-a
    vm_2:
      cloud: AWS
      cidr: 192.168.1.0/24
      zone: us-east-1b
      vm_spec:
        AWS:
            machine_type: m5d.large
            #machine_type: m1.small # Cluster placement groups are not supported by the 'm1.small'
            #machine_type: m5.large # not listed in aws_virtual_machine.py
            #machine_type: t2.micro
            #zone: us-west1-c
